### ISSUE TITLE
Убрать ошибку на windows

### ISSUE THREAD

**Issue by Traineratwot** [webnitros/CronTabManager#2]
\core\components\crontabmanager\model\crontabmanagerhandler.class.php:84

```php
$this->crontab->file_crontab_path = $this->CrontabManager->config['schedulerPath'] . '/crontabs/' . ($_SERVER['USER'] ?? 'cron');
```

\core\components\crontabmanager\model\crontabmanager.class.php:362
```php
 $path = $this->config['schedulerPath'] . '/crontabs/' . ($_SERVER['USER'] ?? 'cron');
```
\assets\components\crontabmanager\cron_connector.php:8
```php
$scheduler_path = preg_replace('/[^a-zA-Z0-9\-\.:_]/', DIRECTORY_SEPARATOR, $_REQUEST['scheduler_path']);
```

На Windows конечно нет crontab но просто чтобы не выдавал непонятную ошибку из-за того что на windows не существует $_SERVER['USER']

**Comment by webnitros** [comment]
Спасибо)
Внесу в следующую версию
